[package]
name = "scalarff"
version = "0.1.0"
edition = "2021"

[lib]

[dependencies]
anyhow = "1.0.86"
twenty-first = "0.41.0"
ark-ff = "=0.4.1"
ark-bn254 = "0.4.0"
ark-std = "0.4.0"
curve25519-dalek = { version = "4.1.3", features = ["group"] }
ff = "0.13.0"
num-bigint = "0.4.6"
num-integer = "0.1.46"
colored = "2.1.0"
