version: 2.1
workflows:
  all:
    jobs:
      - lint
      - clippy
      - tests:
          matrix:
            parameters:
              rust-version: ["stable", "beta", "nightly"]
      - example-residues:
          matrix:
            parameters:
              rust-version: ["stable", "beta", "nightly"]

step_defs:
  - run: &rust_version
      name: Set Rust version stable
      command: |
        curl -o rustup https://sh.rustup.rs
        bash rustup -y
        . "$HOME/.cargo/env"
        rustup update << parameters.rust-version >>
        rustup default << parameters.rust-version >>
        rustup component add clippy
  - run: &build_version_stable
      name: Set Rust version
      command: |
        curl -o rustup https://sh.rustup.rs
        bash rustup -y
        . "$HOME/.cargo/env"
        rustup update stable
        rustup default stable
        rustup component add clippy

jobs:
  clippy:
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      - run: *build_version_stable
      - run:
          name: Clippy
          command: cargo clippy --features=oxfoi,alt_bn128,curve25519
  lint:
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      - run: *build_version_stable
      - run:
          name: Lint
          command: cargo fmt --all -- --check
  tests:
    parameters:
      rust-version:
        type: string
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      - run: *rust_version
      - run:
          name: Test
          command: cargo test --release --features=oxfoi,curve25519,alt_bn128
      - run:
          name: Build wasm32
          command: cargo build --target=wasm32-unknown-unknown --features=oxfoi,curve25519,alt_bn128

  example-residues:
    parameters:
      rust-version:
        type: string
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      - run: *rust_version
      - run:
          name: Build
          command: cargo build --release
      - run:
          name: Run example
          command: cargo run --example 1000_residues --release
